#! /bin/sh
cd /usr/lib
if [ -e "libelementary-ver-pre-svn-07.so.0" ]; then
	echo "libelm 07.so file exists"
else
	echo "creating libelm 07.so file"
fi

ln -sf libelementary-ver-pre-svn-09.so.0 libelementary-ver-pre-svn-07.so.0
